[package]
name = "htsget-indexer"
version = "0.1.0"
authors = ["Roman Valls Guimera <brainstorm@nopcode.org>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.102", features = ["derive"] }
serde_json = "1.0.41"
rust-htslib = "0.26.0"
snafu = "0.6.0"